name: cb_intros
description: "A better way to introduce users to your app. A circular bottom curve and circular button with nice transitions."
version: 0.1.3
homepage: https://github.com/connelevalsam/cb-intros

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/test_img1.JPG
    - assets/images/test_img2.JPG

